version: "3.7"

services:
  webapp-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: game-server-img
    container_name: game-dice-express
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
